site_name: Shopware 6 Plugin Dokumentationen
theme:
  name: 'material'
  palette:
    scheme: flink
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.indexes
  language: de
extra_css:
  - css/extra.css
markdown_extensions:
  - fenced_code
nav:
  - Übersicht:
    - Übersicht: index.md
    # - Kontakt: contact.md
    - Zum Community Store: https://store.shopware.com/flink.html#manuExtensions
  - Dokumentationen:
    - Persönliche Begrüßung:
      - Beschreibung: plugins/FlinkFriendlyGreeting/index.md
      # - Installation: plugins/FlinkFriendlyGreeting/installation.md
      - Konfiguration: plugins/FlinkFriendlyGreeting/configuration.md
      # - FAQ: plugins/FlinkFriendlyGreeting/faq.md
    - Sprungmarken:
      - Beschreibung: plugins/FlinkCmsAnchor/index.md
      # - Installation: plugins/FlinkCmsAnchor/installation.md
      - Konfiguration: plugins/FlinkCmsAnchor/configuration.md
      # - FAQ: plugins/FlinkCmsAnchor/faq.md
    - Responsives Ein-/Ausblenden:
      - Beschreibung: plugins/FlinkCmsResponsiveHelper/index.md
      # - Installation: plugins/FlinkCmsResponsiveHelper/installation.md
      - Konfiguration: plugins/FlinkCmsResponsiveHelper/configuration.md
      # - FAQ: plugins/FlinkCmsResponsiveHelper/faq.md
    - Produkt Schnellansicht:
      - Beschreibung: plugins/FlinkQuickView/index.md
      # - Installation: plugins/FlinkQuickView/installation.md
      - Konfiguration: plugins/FlinkQuickView/configuration.md
      # - FAQ: plugins/FlinkQuickView/faq.md
    - Größentabellen:
      - Beschreibung: plugins/FlinkSizeCharts/index.md
      # - Installation: plugins/FlinkSizeCharts/installation.md
      - Konfiguration: plugins/FlinkSizeCharts/configuration.md
      # - FAQ: plugins/FlinkSizeCharts/faq.md
    - Reponsive Grid Builder:
      - Beschreibung: plugins/FlinkCmsGridBuilder/index.md
      # - Installation: plugins/FlinkCmsGridBuilder/installation.md
      - Konfiguration: plugins/FlinkCmsGridBuilder/configuration.md
      # - FAQ: plugins/FlinkCmsGridBuilder/faq.md
